export const USER_POSTS = [
  {
    id: 1,
    profileImage: require('../../assets/images/default_profile.png'),
    username: 'Abdullah',
    location: 'Jordan',
    likes: 1200,
    comments: 50,
    bookmarks: 20,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 2,
    username: 'Ahmadd.heem',
    profileImage: require('../../assets/images/default_profile.png'),

    location: 'Amman',
    likes: 20,
    comments: 5,
    bookmarks: 2,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 3,
    username: 'Loloas',
    profileImage: require('../../assets/images/default_profile.png'),

    location: 'New york',
    likes: 1,
    comments: 0,
    bookmarks: 0,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 4,
    username: 'Nikimi',
    profileImage: require('../../assets/images/default_profile.png'),

    location: 'Japan',
    likes: 15000,
    comments: 200,
    bookmarks: 100,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 5,
    username: 'The Primegan',
    profileImage: require('../../assets/images/default_profile.png'),

    location: 'San Franseco',
    likes: 12,
    comments: 1,
    bookmarks: 0,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 6,
    username: 'CodeNinja',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'Seattle',
    likes: 45,
    comments: 8,
    bookmarks: 3,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 7,
    username: 'DesignMaster',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'Portland',
    likes: 67,
    comments: 12,
    bookmarks: 5,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 8,
    username: 'TechExplorer',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'Austin',
    likes: 89,
    comments: 15,
    bookmarks: 7,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 9,
    username: 'CreativeGenius',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'Chicago',
    likes: 103,
    comments: 21,
    bookmarks: 9,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 10,
    username: 'DevGuru',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'New York',
    likes: 132,
    comments: 28,
    bookmarks: 12,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 11,
    username: 'UXWizard',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'Denver',
    likes: 156,
    comments: 14,
    bookmarks: 8,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 12,
    username: 'AlgoMaster',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'Boston',
    likes: 78,
    comments: 9,
    bookmarks: 4,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 13,
    username: 'FrontendPro',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'Miami',
    likes: 201,
    comments: 31,
    bookmarks: 15,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 14,
    username: 'DataScientist',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'San Diego',
    likes: 93,
    comments: 11,
    bookmarks: 6,
    postImage: require('../../assets/images/default_post.png'),
  },
  {
    id: 15,
    username: 'CloudArchitect',
    profileImage: require('../../assets/images/default_profile.png'),
    location: 'Washington DC',
    likes: 117,
    comments: 19,
    bookmarks: 10,
    postImage: require('../../assets/images/default_post.png'),
  },
];
